project:
  type: website

website:
  title: "Matt McClellan"
  navbar:
    left:
      - text: Blog
        href: blog.qmd
      - text: Writing
        href: writing.qmd
      - text: Resume
        href: https://mrmcclellan.github.io/resume/
    right:
#      - icon: github
#        href: https://github.com/
#      - icon: twitter
#        href: https://twitter.com
      - icon: linkedin
        href: https://linkedin.com/in/matthew-mcclellan-zzz
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

